### ISSUE TITLE
Could you open source code for the other three attack examples of rowhammer

### ISSUE THREAD

**Issue by zaxfenfeiyu** [HexHive/HexPADS#3]
I'm also interested in attack with cache characteristics, I want to find several attack examples with cache features. The rowhammer can be found on github, but the other three cannot. So, could you open source code for the other three attack examples or just list hyperlinks. Thank you very much.

**Comment by gannimo** [comment]
See the note:

```
CAIN was developed by Antonio Barresi, C6 by Clementine Maurice, CSC by Daniel Grauss, and rowhammer by P0 at Google. The source code of their software can be found in their repositories. The test directory contains pre-compiled versions for x86-64 on Ubuntu 15.10.
```

Please ask the respective authors about the source code :)
